const courses = [
  { title:"MS-CIT", tag:"Flagship", hrs:"120 hrs", sector:"IT Literacy", img:"https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&q=80", desc:"Maharashtra's #1 IT literacy course, launched in 2001. Covers computer basics, internet, MS Office, email and digital safety. Over 15 million learners certified across Maharashtra.", details:["Duration: 120 Hours","Certification: MKCL / YCMOU","Mode: Lab + eLearning (ERA)","Eligibility: 10th Pass","Exam: Online Assessment"] },
  { title:"Advanced Excel", tag:"Financial", hrs:"120 hrs", sector:"Financial Accounting", img:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80", desc:"Master data analysis, pivot tables, VLOOKUP, charts, macros and advanced formulas. Essential for finance, banking and office professionals.", details:["Duration: 120 Hours","Certification: MKCL / YCMOU","Mode: Lab-based Practical","Eligibility: 10th Pass","Job Roles: Data Analyst, Accountant"] },
  { title:"Tally Prime with GST", tag:"Accounting", hrs:"120 hrs", sector:"Financial Accounting", img:"https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80", desc:"Complete accounting with Tally Prime — GST filing, invoicing, payroll, banking and financial statements. Most in-demand skill for commerce graduates.", details:["Duration: 120 Hours","Certification: MKCL","Mode: Lab Practical","Eligibility: 10th + Commerce preferred","Job Roles: Accountant, GST Consultant"] },
  { title:"Graphic Designing", tag:"Design", hrs:"120 hrs", sector:"Digital Designing", img:"https://images.unsplash.com/photo-1558655146-d09347e92766?w=600&q=80", desc:"Adobe Photoshop, Illustrator, CorelDRAW — learn to create logos, banners, social media graphics and marketing materials for clients worldwide.", details:["Duration: 120 Hours","Certification: MKCL / YCMOU","Mode: Lab-based Creative","Eligibility: 12th Pass","Job Roles: Graphic Designer, Freelancer"] },
  { title:"Data Entry & Management", tag:"Back Office", hrs:"60 hrs", sector:"Back Office", img:"https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80", desc:"Master fast and accurate data entry, database management, MS Word, Excel and typing skills. Perfect for government and private sector jobs.", details:["Duration: 60 Hours","Certification: MKCL","Mode: Lab-based","Eligibility: 10th Pass","Job Roles: Data Entry Operator, Clerk"] },
  { title:"English Communication", tag:"Front Office", hrs:"120 hrs", sector:"Front Office", img:"https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&q=80", desc:"MKCL's flagship English course — grammar, spoken English, business communication, email writing and presentation skills for career growth.", details:["Duration: 120 Hours","Certification: MKCL / YCMOU","Mode: ERA eLearning + Lab","Eligibility: 10th Pass","Job Roles: Receptionist, Customer Service"] },
  { title:"Digital Marketing", tag:"Freelancing", hrs:"120 hrs", sector:"Digital Freelancing", img:"https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=600&q=80", desc:"SEO, Google Ads, Facebook Marketing, Instagram, YouTube, email marketing and analytics. Launch your own agency or work as a freelancer.", details:["Duration: 120 Hours","Certification: MKCL / YCMOU","Mode: Online + Practical","Eligibility: 12th Pass","Job Roles: Digital Marketer, SEO Expert"] },
  { title:"AutoCAD", tag:"Design", hrs:"120 hrs", sector:"Digital Creative Art", img:"https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=80", desc:"2D and 3D computer-aided design for architecture, civil engineering and interior design. Create professional floor plans and technical drawings.", details:["Duration: 120 Hours","Certification: MKCL / YCMOU","Mode: Lab-based","Eligibility: 12th / Engineering","Job Roles: CAD Operator, Draftsman"] },
  { title:"Web Designing", tag:"Tech", hrs:"120 hrs", sector:"Software Development", img:"https://images.unsplash.com/photo-1547658719-da2b51169166?w=600&q=80", desc:"HTML5, CSS3, JavaScript, responsive design and WordPress. Build stunning websites and launch your freelance career in web development.", details:["Duration: 120 Hours","Certification: MKCL / YCMOU","Mode: Lab Practical","Eligibility: 12th Pass","Job Roles: Web Designer, Freelancer"] },
  { title:"Python Programming", tag:"Coding", hrs:"120 hrs", sector:"Software Development", img:"https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&q=80", desc:"Python fundamentals, data science libraries, web frameworks (Django/Flask) and automation scripts. Most popular programming language worldwide.", details:["Duration: 120 Hours","Certification: MKCL / YCMOU","Mode: Lab-based Coding","Eligibility: 12th / Engineering","Job Roles: Python Developer, Data Analyst"] },
  { title:"AI & Machine Learning", tag:"Advanced", hrs:"120 hrs", sector:"Data Science", img:"https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&q=80", desc:"Explore AI concepts, ML models, 100+ AI tools, ChatGPT, automation and ethical AI. Stay ahead in the age of artificial intelligence.", details:["Duration: 120 Hours","Certification: MKCL / YCMOU","Mode: ERA + Lab","Eligibility: 12th Pass","Job Roles: AI Analyst, Prompt Engineer"] },
  { title:"Cyber Security", tag:"Security", hrs:"120 hrs", sector:"IT Hardware & Security", img:"https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&q=80", desc:"Digital safety, ethical hacking basics, network security, cyber laws and cyber resilience. Protect yourself and organizations from online threats.", details:["Duration: 120 Hours","Certification: MKCL / YCMOU","Mode: Lab-based","Eligibility: 12th Pass","Job Roles: Security Analyst, Network Admin"] },
  { title:"DTP (Adobe & CorelDRAW)", tag:"Design", hrs:"120 hrs", sector:"Digital Designing", img:"https://images.unsplash.com/photo-1512486130939-2c4f79935e4f?w=600&q=80", desc:"Desktop publishing for print media — brochures, newspapers, books, banners using Adobe InDesign, Photoshop and CorelDRAW professionally.", details:["Duration: 120 Hours","Certification: MKCL / YCMOU","Mode: Lab Creative","Eligibility: 12th Pass","Job Roles: DTP Operator, Print Designer"] },
  { title:"Office Assistance", tag:"Back Office", hrs:"120 hrs", sector:"Back Office", img:"https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80", desc:"Complete Microsoft Office suite — Word, Excel, PowerPoint, Outlook plus soft skills and office management. Ideal for administrative roles.", details:["Duration: 120 Hours","Certification: MKCL / YCMOU","Mode: Lab-based","Eligibility: 10th Pass","Job Roles: Office Assistant, Admin Executive"] },
  { title:"3D Modelling & Animation", tag:"Creative", hrs:"120 hrs", sector:"Digital Creative Art", img:"https://images.unsplash.com/photo-1620674156044-52b714665d46?w=600&q=80", desc:"Create stunning 3D models, animations, rigging and rendering for films, games, architecture and product visualization using industry tools.", details:["Duration: 120 Hours","Certification: MKCL / YCMOU","Mode: Lab Creative","Eligibility: 12th Pass","Job Roles: 3D Artist, VFX Designer"] }
];